Repository koalalu007/resume-maker, pull requests merged in 2023-10, with the labels that each got.

#3 Made Readme
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#14 added live data display
  index.css
  index.html
  index.js
  pdfTamplate.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#15 Add summary-section, fix input-overflow
  index.css
  index.html
  index.js
  pdfTamplate.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#23 FIX#22 : fixed the updation
  index.js
Labels: hacktoberfest, hacktoberfest-accepted

#24 Improved the UI/UX of page
  .vscode/settings.json
  index.css
  index.html
  index.js
  pdfTamplate.html
Labels: hacktoberfest, hacktoberfest-accepted

#32 Added code-of-conduct.md
  Code-Of-conduct.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted
